name: Login to Azure
description: Login to Azure using app registered with Azure AD

# permissions:
#   id-token: write
runs:
  using: composite
  steps:
    - name: Checkout GitHub Actions
      uses: actions/checkout@v3
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
