name: deploy Azure resource
on: workflow_dispatch
jobs:
  login:
    runs-on: ubuntu-latest
    environment:
      name: deploy
    permissions:
      id-token: write
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Show login result
        run: az account show
