on: workflow_dispatch
jobs:
  login:
    runs-on: ubuntu-latest
    environment:
      name: deploy
    permissions:
      id-token: write
    steps:
      - uses: ./../actions/azure-login.yml
      - name: Show sign in result
        run: az account show
