on: workflow_dispatch
jobs:
  login:
    runs-on: ubuntu-latest
    environment:
      name: deploy
    permissions:
      id-token: write
    steps:
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Show sign in result
        run: az account show
